Repository mash-up-kr/DamgleDamgle_iOS, pull requests merged in 2022-07, with the labels that each got.

#2 ✨ Posting 피드면 TableView 생성 (이모티콘 선택 기능 포함)
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=amazing.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=amazing.imageset/icn=amazing.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=amazing_y.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=amazing_y.imageset/icn=amazing_y.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=angry.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=angry.imageset/icn=angry.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=angry_y.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=angry_y.imageset/icn=angry_y.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best.imageset/icn=best.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best_inactive.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best_inactive.imageset/icn=best_inactive.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best_y.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=best_y.imageset/icn=best_y.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=like.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=like.imageset/icn=like.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=like_y.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=like_y.imageset/icn=like_y.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=sad.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=sad.imageset/icn=sad.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=sad_y.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/icn=sad_y.imageset/icn=sad_y.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_list_bg.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_list_bg.imageset/img_list_bg.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_write.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_write.imageset/img_write.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Base.lproj/Main.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RoundView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/SelectableButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Info.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostModel.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingStoryboard.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingViewModel.swift
Labels: Feature ✅

#5 #4 Feature/home view UI
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
Labels: UI 🎨

#3 #1 Feature/location authorization
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Colors.xcassets/dimViewColor.colorset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/FullDimView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/LocationService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/UIViewController+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Enum/LocationAuthorizationStatus.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Info.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
Labels: Feature ✅

#10 📝 PR 리뷰어, 리뷰이 자동 할당 관리해주는 `auto_assign.yml`파일 추가
  .github/auto_assign.yml
Labels: helper💪

#14 #7 Feature/post view UI
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/UIViewController+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
Labels: UI 🎨

#17 ✨ my 화면 상단 및 하단 탭 페이징 UI 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_close.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_close.imageset/icn_close.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_close.imageset/icn_close@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_close.imageset/icn_close@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/icn_mypage.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/icn_mypage@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/icn_mypage@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Base.lproj/Main.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Colors.xcassets/grey1000.colorset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Protocol/StoryboardBased.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/Array+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/DGButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/My.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/MyPostListViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/MyViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/SettingViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/UIColor+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/ViewController.swift
Labels: UI 🎨

#12 [#11] OnboardingNickname UI 구현 - 스토리보드
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Group 189.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Group 189.imageset/Group 189.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Vector 25.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Vector 25.imageset/Vector 25.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Vector 26.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Vector 26.imageset/Vector 26.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/autorenew-1.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/autorenew-1.imageset/autorenew.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/image 130.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/image 130.imageset/image 130.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_no_emoji_ios.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/img_no_emoji_ios.imageset/img_no_emoji_ios.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Onboarding/OnboardingNicknameStoryboard.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Onboarding/OnboardingNicknameViewController.swift
Labels: UI 🎨

#13 🐛PostringView 내부 Icons 버튼 애니메이션 버그 해결
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Info.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingStoryboard.storyboard
Labels: Bug 🐞, later review 🙇🏻‍♀️

#19 Feature/flow
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Base.lproj/Main.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/My.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/Nickname.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/ViewController.swift
Labels: Feature ✅

#20 #13 🐛PR 내용 반영
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
Labels: Bug 🐞

#22 ✨ setting 화면 UI 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/Rectangle 107.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/Rectangle 107.imageset/Rectangle 107.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/Rectangle 107.imageset/Rectangle 107@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/Rectangle 107.imageset/Rectangle 107@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mydamgle.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mydamgle.imageset/img_mydamgle.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mydamgle.imageset/img_mydamgle@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mydamgle.imageset/img_mydamgle@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mypage_bg.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mypage_bg.imageset/img_mypage_bg.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mypage_bg.imageset/img_mypage_bg@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_mypage_bg.imageset/img_mypage_bg@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_setting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_setting.imageset/img_setting.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_setting.imageset/img_setting@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/img_setting.imageset/img_setting@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/DGButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Info.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/My.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/PostList/MyPostListViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/Setting/SettingViewController.swift
Labels: UI 🎨

#23 ✨Feature/post process UI
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/ContinueButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/String+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/UIViewController+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewModel.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/PostProcess/PostProcess.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/PostProcess/PostProcessViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
Labels: later merge 🤝, UI 🎨

#26 🚀 Feature/add map sdk
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/contents.xcworkspacedata
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/LocationService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Enum/CommonStringResource.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Info.plist
  DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewController.swift
  DamgleDamgle_iOS/Podfile
  DamgleDamgle_iOS/Podfile.lock
Labels: Feature ✅

#30 ✨ 앱 아이콘 및 스플래시 화면 적용
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/100.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/1024.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/114.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/120.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/128.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/144.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/152.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/16.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/167.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/172.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/180.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/196.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/20.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/216.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/256.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/29.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/32.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/40.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/48.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/50.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/512.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/55.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/57.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/58.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/60.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/64.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/72.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/76.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/80.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/87.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/88.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Base.lproj/LaunchScreen.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Lottie/splash.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/SceneDelegate.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Splash/Splash.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Splash/SplashViewController.swift
Labels: UI 🎨

#31 🚀 HomeViewController 타이머 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Custom/ContinueButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Enum/DateIntervalType.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Extension/Date+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Extension/Int+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
Labels: Feature ✅

#33 ✨ APIErrorView UI 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_list_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_list_posting.imageset/img_error_list.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_list_error_bg_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_list_error_bg_posting.imageset/img_list_error_bg.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostErrorTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingStoryboard.storyboard
Labels: UI 🎨

#36 Feature/mypage
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/mystory_reaction.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/mystory_reaction.imageset/Frame 226.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/mystory_reaction.imageset/Frame 226@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/mystory_reaction.imageset/Frame 226@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Model/Reaction.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Model/Story.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/My.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/MyViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/PostList/MyPostListViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/Setting/SettingViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/StoryList/ListEmptyView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/StoryList/MyStoryCollectionViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/StoryList/MyStoryListViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/StoryList/MyStoryListViewModel.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/StoryList/StoryService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Splash/Splash.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Splash/SplashViewController.swift
Labels: UI 🎨

#38 🚀 StoryAPI 구조
  DamgleDamgle_iOS/.swiftlint.yml
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/Model/StoryRequest.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/Story/StoryTarget.swift
Labels: Feature ✅

#28 ✨ Icons 버튼 클릭에 따라 이미지 그려주는 로직 및 UI 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/xcshareddata/xcschemes/DamgleDamgle_iOS.xcscheme
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Group 36979.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Group 36979.imageset/Group 36979.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Group 36980.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Group 36980.imageset/Group 36980.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Rectangle 77.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Rectangle 77.imageset/Rectangle 77.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Vector 25_black.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Vector 25_black.imageset/Vector 25_black.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Vector 26_black_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/Vector 26_black_posting.imageset/Vector 26_black.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_list_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_list_posting.imageset/img_error_list.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_nolist_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_error_nolist_posting.imageset/img_error_nolist.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_gul.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_gul.imageset/img_gul.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_list_error_bg_posting.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_list_error_bg_posting.imageset/img_list_error_bg.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_no_emoji_ios.imageset/Contents.json
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Posting/img_no_emoji_ios.imageset/img_no_emoji_ios.pdf
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/LocationAuthorizationViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RotatableImageView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/RoundLabel.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Components/SelectableButton.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Protocol/CustomViewType.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Protocol/NibBased.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Post/PostViewController.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/ManyIconsView.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoDataView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoDataView.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoIconsView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/NoIconsView.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/OneIconView.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/IconsImageView/OneIconView.xib
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostErrorTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostModel.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostTableViewCell.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingMainViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingStoryboard.storyboard
  DamgleDamgle_iOS/DamgleDamgle_iOS/Posting/PostingViewModel.swift
Labels: UI 🎨

#43 🚀 userManager에서 accessToken 관리할 수 있는 기능 구현
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DamgleDamgle_iOS/DamgleDamgle_iOS/Authorization/PushAuthorizationViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Protocol/UserDefaultWrapperable.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/My/Setting/SettingViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Nickname/NicknameViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/User/UserManager.swift
Labels: Feature ✅

#46 🚀 위도/경도 값 → 주소 변환
  .gitignore
  DamgleDamgle_iOS/DamgleDamgle_iOS.xcodeproj/project.pbxproj
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Authorization/icn=location.imageset/icn=location@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/CommonIcon/icn_error.imageset/icn_error@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_picker_me.imageset/btn_picker_me@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_point.imageset/btn_point@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/btn_refresh.imageset/btn_refresh@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_mypage.imageset/icn_mypage@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/icn_paint.imageset/icn_paint@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Home/indicatorBar.imageset/Line 209@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/icn_mypage@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/My/icn_profileImage.imageset/icn_mypage@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write.imageset/img_write@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/img_write_bg.imageset/img_write_bg@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_fail.imageset/btn_picker@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@1x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@2x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Assets.xcassets/Post/post_success.imageset/btn=write_me@3x.png
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Define/LocationService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Global/Extension/Bundle+Extension.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Home/HomeViewController.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/ReverseGeocoding/GeocodingService.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/ReverseGeocoding/GeocodingTarget.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/ReverseGeocoding/Model/GeocodingRequest.swift
  DamgleDamgle_iOS/DamgleDamgle_iOS/Network/ReverseGeocoding/Model/GeocodingResponse.swift
Labels: Feature ✅
